DROP TABLE IF EXISTS ParticipantData;

CREATE TABLE ParticipantData (
    consent VARCHAR(255),
    duration VARCHAR(255),
    end_date VARCHAR(255),
    finished VARCHAR(255),
    progress VARCHAR(255),
    gender VARCHAR(255),
    citizenship VARCHAR(255),
    years_in_usa VARCHAR(255),
    school VARCHAR(255),
    education_level VARCHAR(255),
    parent_education VARCHAR(255),
    employment VARCHAR(255),
    household_inc VARCHAR(255),
    household_size VARCHAR(255),
    household_under_18 VARCHAR(255),
    political_party VARCHAR(255),
    birth_year VARCHAR(255),
    political_orientation VARCHAR(255),
    religious VARCHAR(255),
    religious_group VARCHAR(255),
    pet VARCHAR(255),
    surroundings VARCHAR(255),
    hispanic VARCHAR(255),
    race_american_native VARCHAR(255),
    race_asian VARCHAR(255),
    race_black VARCHAR(255),
    race_pacific VARCHAR(255),
    race_white VARCHAR(255),
    race_none VARCHAR(255),
    marital VARCHAR(255),
    english_first VARCHAR(255),
    english_skill VARCHAR(255),
    home_lang VARCHAR(255),
    home_lang_other VARCHAR(255),
    zip_code VARCHAR(255),
    recorded_date VARCHAR(255),
    response_id VARCHAR(255),
    start_date VARCHAR(255)
);